name: ci

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: "Create binaries"
        run: npm run bundle
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: TwitchMidiBot*


